### ISSUE TITLE
Please adapt to changes in iOS17 & macOS 14

### ISSUE THREAD

**Issue by nkalvi** [SwiftUI-Plus/Connections#2]
https://github.com/SwiftUI-Plus/Connections/blob/b7a67d9001bfc8c41dbffcda4111cfacb37da863/Sources/Connections/Support/Identifiable.swift#L5

Please update this to work with upcoming changes:
[id | Apple Developer Documentation](https://developer.apple.com/documentation/contacts/cncontact/4213327-id)

> @objc
> dynamic var id: [UUID](https://developer.apple.com/documentation/foundation/uuid) { get }
> Relationships
> From Protocol
> Identifiable

**Comment by shaps80** [comment]
I already fixed this in the latest release. Contributions always welcome btw, rather than demands ;)

**Comment by nkalvi** [comment]
I'm sorry, didn't realize I sounded demanding ;) 

`1.2.0` fails to compile:
```
Command SwiftCompile failed with a nonzero exit code

/Connections/Fetch/FetchContact.swift:23:31 'ID' is only available in iOS 17 or newer
/Connections/Fetch/FetchContactList.swift:118:33 'ID' is only available in iOS 17 or newer
/Connections/Fetch/FetchContainerList.swift:57:42 'ID' is only available in iOS 17 or newer
/Connections/Support/Identifiable.swift:4:1 Type 'CNContact' does not conform to protocol 'Identifiable'
``` 

I'll submit a PR later.

**Comment by shaps80** [comment]
Appreciate it. I’m surprised as I saw this and thought I’d resolved. Perhaps the fix only worked in the previous beta. Thansk.
